### ISSUE TITLE
Add the possibility to print the whole book to PDF

### ISSUE THREAD

**Issue by AndreaPi** [tum-pbs/pbdl-book#1]
Hi,

thank you so much for this wonderful resource! What about adding the possibillity to print the whole book to PDF, or to some other format such as epub, mobi, etc.? This would be very useful for people who want to read it offline. See for example a similar issue for another HTML book:

https://github.com/chiphuyen/ml-interviews-book/issues/7

**Comment by tum-pbs** [comment]
Yes, it's in the works - stay tuned, a first pdf version should be up in a few days

**Comment by tum-pbs** [comment]
Online now at: https://arxiv.org/pdf/2109.05237.pdf
