### ISSUE TITLE
cannot reproduce results burgers

### ISSUE THREAD

**Issue by mlttac** [tum-pbs/pbdl-book#11]
Hi, 
I cannot reproduce the results of the notebook of chapter 8 on burgers optimization (diffphys-code-burgers.ipynb). 
The gradient with math.gradients(loss, values) gives completely different values and then the optimization steps return a loss of nan. 
How can I reproduce the same results of the book?

**Comment by thunil** [comment]
Thanks for the notice, it should be working now. phiflow recently fixed its Laplacian, which affected the "diffuse()" function used in the Burgers example. So now the viscosity NU in the Burgers examples requires an additional (1/N) factor to reproduce the old results.
