### ISSUE TITLE
Issue on page /physicalloss-code.html

### ISSUE THREAD

**Issue by dhruvbalwada** [tum-pbs/pbdl-book#13]
The terminology/notation in the first paragrph of the Formulation section seems very confusing, and does not seem to align up with how things are defined in Models and equations section (or in the Notations section). 

E.g. x is defined as neural network input or spatial location in Notation, but here it seems to be a solution to u. Should x actually be f(x;$\theta$) or u(x; $\theta$)?

**Comment by thunil** [comment]
Thanks for pointing this out! Is the updated version at http://physicsbaseddeeplearning.org/physicalloss-code.html clearer?
