### ISSUE TITLE
cant reproduce the result of  Reducing Numerical Errors with Deep Learning

### ISSUE THREAD

**Issue by dgy-0730** [tum-pbs/pbdl-book#14]
hello,when i try to reproduce the result of the Reducing Numerical Errors with Deep Learning,i meet some problem that cant make the trainning runs well,the error saids:
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
Traceback (most recent call last):
  File "C:/Users/XXX/XXX/PBDL/NS/NS_DPNN_org.py", line 380, in <module>
    loss = training_step_jit(dens_gt, vel_gt, re_nr, math.tensor(steps))
  File "E:\anaconda3\envs\PBDL\lib\site-packages\phi\math\_functional.py", line 149, in __call__
    native_result = self.traces[key](*natives)
  File "E:\anaconda3\envs\PBDL\lib\site-packages\phi\tf\_tf_backend.py", line 106, in <lambda>
    return lambda *args: self.as_registered.call(compiled, *args, name=f"run jit-compiled '{f.__name__}'")
  File "E:\anaconda3\envs\PBDL\lib\site-packages\phi\math\backend\_backend.py", line 306, in call
    return f(*args)
  File "E:\anaconda3\envs\PBDL\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "E:\anaconda3\envs\PBDL\lib\site-packages\tensorflow\python\eager\execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: {{function_node __inference_native(training_step)_41157}} JIT compilation failed.
	 [[{{node mod_2}}]] [Op:__inference_native(training_step)_41157]

firstly i think its beacause of my tensorflow and cuda are not suitable, but i have successed with the code of the "Burgers Optimization with a Physics-Informed NN", the trainning runs well in this course.
im very confussed with this, please give me a hand ,thanks very much!

**Comment by thunil** [comment]
This looks like a problem with your CUDA installation. Please try running the code example on Colab.
