### ISSUE TITLE
Question with a photo in 3.4.4 RANS training data

### ISSUE THREAD

**Issue by Gxinhu** [tum-pbs/pbdl-book#17]
![photo](https://user-images.githubusercontent.com/12217422/198838307-02fbeb02-2b4d-491b-ae0a-0edd290dfb2f.png)
I have a question about this photo in 3.4.4. The in-uy inside of the airfoil shape is $1.0$, but I find the following sentence in the [original paper](https://ge.in.tum.de/publications/2018-deep-flow-pred/) of the **Supervised training for RANS flows around airfoils** example.
> Both velocity channels are initialized to the x and y component of the freestream conditions, respectively, with a zero velocity inside of the airfoil shape.

Maybe the in-uy inside of the airfoil shape should by $0.0$. I am a newbie in the filed of Physic-based Deep Learning, if I said something please forgive me. 
Thank you for your works.

**Comment by thunil** [comment]
You're right, but this comes from the visualization. As you can see in the code right above for showSbs(), each image is normalized separately in terms of min/max content. If you look at the raw data, you'll find that it's zero inside the airfoil (alternatively you can disable the min, mean,max normalization of showSbs)
