### ISSUE TITLE
module 'phi.math' has no attribute 'expand_dims'

### ISSUE THREAD

**Issue by JZK00** [tum-pbs/pbdl-book#19]
My version：tensorflow 2.6.2；phiflow  2.2.0...

And when I run the code in "Burgers Optimization with a Physics-Informed NN",  the AttributeError showed "module 'phi.math' has no attribute 'expand_dims' ".  I don't know if it's a version problem.

This section cannot be run locally, so I'm missing two files "burgers-groundtruth-solution.npz" and "burgers-pinn-solution.npz". I would like to ask if you can provide these two files so that I can run the following comparison locally? Thanks so much to you.

**Comment by thunil** [comment]
This notebook unfortunately needs an older version of phiflow, as you can see from the pip install command:
!pip install --quiet phiflow==1.5.1

And good idea to provide the data files, we'll keep that in mind for the next update!
