### ISSUE TITLE
Possible loss of "t“ in a equation

### ISSUE THREAD

**Issue by cloudbird7** [tum-pbs/pbdl-book#22]
Hello!

In the section of `Burgers Optimization with a Physics-Informed NN` > `Preliminaries`, there is a sentence of "We'll also define the `boundary_tx` function which gives an array of constraints for the solution (all for $=0.5$ in this example)". I think that $=0.5$ should possibly be $t=0.5$.

Thank you!

**Comment by thunil** [comment]
Thanks for pointing this out, it's fixed (for now only in the git repo)!
