### ISSUE TITLE
minor typo in intro-teaser notebook

### ISSUE THREAD

**Issue by josephko91** [tum-pbs/pbdl-book#26]
In the plot for the Standard Approach in the teaser parabola example, the x and y axis labels appear to be mislabeled. 
Minor typo fix: 
```
plt.xlabel('x')
plt.ylabel('y')
 ```
<img width="429" alt="image" src="https://github.com/user-attachments/assets/29428fa1-6f93-4f70-a6b6-609985a086e0">

**Comment by thunil** [comment]
Good catch, thanks for pointing this out!
