### ISSUE TITLE
About the overview

### ISSUE THREAD

**Issue by zjuidiot** [tum-pbs/pbdl-book#27]
In the overview "Simple Forward Simulation of Burgers Equation with phiflow", the author said that "These two properties are the main difference between a tensor and a grid: the latter has boundary conditions and a physical extent." I suspect that this is not a physical meaning, but rather a type definition in Phiflow. Or maybe my understanding of this physics problem is not clear enough. Can someone teach me how to understand this sentence?

**Comment by thunil** [comment]
Thanks for pointing this out, I've clarified it now.
