### ISSUE TITLE
Is a PyTorch version in the horizon?

### ISSUE THREAD

**Issue by ghosh-r** [tum-pbs/pbdl-book#4]
This project piques my interest, and I would like to read through the book. I have worked on projects with TF/Keras before.

But I would really like a PyTorch version.

Do you have any updates on that?

I would be able to suggest this book to many people if it had a PyTorch version.

Thanks for this great project.

**Comment by thunil** [comment]
Actually, some of the notebooks are already using pytorch, e.g.: https://www.physicsbaseddeeplearning.org/diffphys-code-ns.html 

That being said, at the moment we're not planning to provide every notebook for both TF and pytorch. phiflow (https://github.com/tum-pbs/PhiFlow), which is used for all the differentiable physics examples, supports pytorch, TF and JAX, though. So it shouldn't be too hard to get the code examples working in pytorch.

**Comment by ghosh-r** [comment]
@thunil thanks. Appreciate the info.
